# This file contains all the aliases I use in my bash shell.

# bash aliases
alias b='bash'
alias sb='source ~/.bashrc'
alias sbp='source ~/.bash_profile'
alias sbrc='source ~/.bashrc'

# # ls aliases
# alias ll='ls -alF'
# alias la='ls -A'
# alias lah='ls -Ahl'
# alias l='ls -CF'
# Changing "ls" to "exa"
alias ls='exa -al --color=always --group-directories-first' # my preferred listing
alias la='exa -a --color=always --group-directories-first'  # all files and dirs
alias lah='exa -ahl --color=always --group-directories-first' # all files and dirs, long format
alias ll='exa -l --color=always --group-directories-first'  # long format
alias lt='exa -aT --color=always --group-directories-first' # tree listing
alias l.='exa -a | egrep "^\."'


# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# cd aliases
alias ..='cd ..'            
alias ...='cd ../..'            
alias ....='cd ../../..'    
alias ~='cd ~'

# git aliases
alias g='git'
alias gs='git status'
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit'
alias gcm='git commit -m'
alias gca='git commit --amend'
alias gcam='git commit --amend -m'
alias gpom='git push origin master'
# git
alias addup='git add -u'
alias addall='git add .'
alias branch='git branch'
alias checkout='git checkout'
alias clone='git clone'
alias commit='git commit -m'
alias fetch='git fetch'
alias pull='git pull origin'
alias push='git push origin'
alias stat='git status'  # 'status' is protected name so using 'stat' instead
alias tag='git tag'
alias newtag='git tag -a'


# neovim aliases
alias v='nvim'
alias v.='nvim .'
alias n='nvim'
alias n.='nvim .'
alias nv='nvim'
alias nv.='nvim .'
alias vi='nvim'
alias vi.='nvim .'
alias vim='nvim'
alias vim.='nvim .'

# tmux aliases
alias t='tmux'
alias ta='tmux attach'
alias tn='tmux new'
alias tns='tmux new -s'
alias tl='tmux ls'
alias tk='tmux kill-session'
alias ts='tmux switch -t'
alias tks='tmux kill-session -t'
alias tns='tmux new-session -s'

# python aliases
alias py='python3'
alias py2='python2'
alias py3='python3'
alias pip='pip3'
alias pip2='pip2'
alias pip3='pip3'

# emacs and doom aliases
alias emacs='emacsclient -c -n'
alias emacst='emacsclient -nw'
alias doomt='emacsclient28 -c -n'
alias doomt='emacsclient28 -nw'


